/**
 * Database Seeder
 * Creates default users + 146 seed leads on first startup.
 * Only runs if the table is empty — safe to call on every boot.
 */

const { User, Lead } = require("../models");

async function seedDatabase() {
  try {
    // ── Seed Users ──────────────────────────────────────────────
    const userCount = await User.count();
    if (userCount === 0) {
      console.log("🌱 Seeding users...");
      await User.bulkCreate([
        {
          username: "ravi",
          password: "Frontline2026!@#$%",
          displayName: "Ravi",
          role: "admin",
        },
        {
          username: "pam",
          password: "Frontline@2026!@#$%",
          displayName: "Pam",
          role: "user",
        },
      ], { individualHooks: true });
      console.log("✅ Users created: ravi (admin), pam (user)");
    }

    // ── Seed Leads ──────────────────────────────────────────────
    const leadCount = await Lead.count();
    if (leadCount > 0) {
      console.log(`ℹ️  Leads already exist (${leadCount}). Skipping seed.`);
      console.log("✅ Database seed complete");
      return;
    }

    console.log("🌱 Seeding 146 leads from Kimi AI research...");

    const today = new Date().toISOString().split("T")[0];
    const d = (n) => {
      const dt = new Date();
      dt.setDate(dt.getDate() + n);
      return dt.toISOString().split("T")[0];
    };

    const note = (text, person = "Kimi Import") => [
      { date: today, person, text },
    ];

    const seedLeads = [
      // ══════════════════════════════════════════════════════
      // SOCCER MODULE — MLS / Fan Groups / Youth / Tournaments
      // ══════════════════════════════════════════════════════
      {
        legacyId: 1,
        org: "Sons of Ben (SOB)",
        contact: "Supporter Group President",
        email: "info@sonsofben.com",
        website: "https://sonsofben.com",
        social: "@sonsofben",
        type: "Union Fan Group",
        module: "soccer",
        status: "New",
        gamedate: "2025-06-07",
        source: "sonsofben.com",
        followup: d(2),
        notes: note(
          "Philadelphia Union official supporter group. Massive reach — target pre/post-match events at Frontline.",
        ),
      },
      {
        legacyId: 2,
        org: "FC Dallas Supporters",
        contact: "Away Supporters Coordinator",
        website: "https://fcdallas.com",
        social: "@FCDallasFC",
        type: "Visiting MLS Team",
        module: "soccer",
        status: "New",
        gamedate: "2025-06-14",
        source: "mlssoccer.com",
        followup: d(2),
        notes: note(
          "Visiting MLS team supporters group. Offer group dining package for away trip.",
        ),
      },
      {
        legacyId: 3,
        org: "Delaware Valley Futsal Cup",
        contact: "Tournament Director",
        website: "https://dvfutsal.com",
        social: "@DVFutsal",
        type: "Tournament",
        module: "soccer",
        status: "Booked",
        gamedate: "2025-05-24",
        source: "dvfutsal.com",
        followup: "",
        notes: [
          {
            date: d(-3),
            person: "Frontline Staff",
            text: "BOOKED! 60 people Saturday evening. Caribbean buffet + bar tab confirmed.",
          },
        ],
        seqStep: 4,
      },
      {
        legacyId: 4,
        org: "Chester Youth Soccer League",
        contact: "League Director",
        social: "@ChesterYouthSoccer",
        type: "Youth Soccer Team",
        module: "both",
        status: "New",
        gamedate: "2025-05-10",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Chester-based youth league. End-of-season banquet and team celebration potential.",
        ),
      },
      {
        legacyId: 5,
        org: "Philadelphia Union Academy",
        contact: "Academy Director",
        website: "https://philadelphiaunion.com/academy",
        social: "@PhilaUnion",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        gamedate: "2025-06-07",
        source: "philadelphiaunion.com",
        followup: d(3),
        notes: note(
          "MLS academy feeder — youth tournaments and parent appreciation dinners.",
        ),
      },
      {
        legacyId: 6,
        org: "River Towns SC",
        contact: "Club President",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Regional youth soccer club. Target end-of-season banquets.",
        ),
      },
      {
        legacyId: 7,
        org: "Delco Soccer Club",
        contact: "Director of Coaching",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Delaware County youth soccer club with 400+ players. Big banquet potential.",
        ),
      },
      {
        legacyId: 8,
        org: "Chester FC",
        contact: "Club Manager",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Local Chester football club — strong community ties to Frontline neighborhood.",
        ),
      },
      {
        legacyId: 9,
        org: "Keystone FC",
        contact: "Events Coordinator",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Pennsylvania-based competitive club. Recruitment events and showcase weekends.",
        ),
      },
      {
        legacyId: 10,
        org: "Delaware County Soccer Association",
        contact: "Executive Director",
        website: "https://delsoccer.com",
        type: "Tournament",
        module: "soccer",
        status: "New",
        source: "delsoccer.com",
        followup: d(3),
        notes: note(
          "County governing body. Tournament banquets and referee appreciation dinners.",
        ),
      },
      {
        legacyId: 11,
        org: "Eastern Pennsylvania Youth Soccer",
        contact: "Tournament Committee",
        website: "https://epys.org",
        type: "Tournament",
        module: "soccer",
        status: "New",
        source: "epys.org",
        followup: d(4),
        notes: note(
          "Largest youth soccer org in region. State cup travel groups + banquets.",
        ),
      },
      {
        legacyId: 12,
        org: "Philadelphia Lone Star FC",
        contact: "Supporter Group Lead",
        type: "Supporter Club",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Historic Philly soccer club. Game day gatherings and supporter events.",
        ),
      },
      {
        legacyId: 13,
        org: "Union Ultras",
        contact: "Capo / Group Leader",
        social: "@UnionUltras",
        type: "Union Fan Group",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(1),
        notes: note(
          "Passionate Union supporter group — pre-match pub crawl partnership opportunity.",
        ),
      },
      {
        legacyId: 14,
        org: "The River End",
        contact: "Membership Coordinator",
        type: "Union Fan Group",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Union supporter section. Match-day specials and meetup hosting.",
        ),
      },
      {
        legacyId: 15,
        org: "Chester Lacrosse Club",
        contact: "Head Coach",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Multi-sport club expanding into soccer. Team dinners and fundraiser events.",
        ),
      },

      // ══════════════════════════════════════════════════════
      // CATERING MODULE — Churches, Nonprofits, Schools, etc.
      // ══════════════════════════════════════════════════════
      {
        legacyId: 16,
        org: "Chester Senior Center",
        contact: "Senior Programs Director",
        type: "Senior Program",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(2),
        notes: note(
          "Weekly senior meal programs and holiday banquets. Repeat revenue potential.",
        ),
      },
      {
        legacyId: 17,
        org: "Chester-Upland School District",
        contact: "District Events Coordinator",
        website: "https://chesterupland.org",
        type: "School",
        module: "catering",
        status: "New",
        gamedate: "2026-04-25",
        source: "Catering CRM",
        followup: d(2),
        notes: note(
          "Spring Summit at STEM Academy. Contact for future events and staff appreciation dinners.",
        ),
      },
      {
        legacyId: 18,
        org: "Widener University – Student Affairs",
        contact: "Director of Student Affairs",
        website: "https://widener.edu",
        type: "University",
        module: "catering",
        status: "New",
        gamedate: "2026-05-12",
        source: "Catering CRM",
        followup: d(2),
        notes: note(
          "Commencement May 12-14. Target department dinners and president receptions.",
        ),
      },
      {
        legacyId: 19,
        org: "Shiloh Baptist Church",
        contact: "Pastor / Events Chair",
        type: "Church",
        module: "catering",
        status: "New",
        gamedate: "2026-05-15",
        source: "Catering CRM",
        followup: d(1),
        notes: note(
          "Senior Fellowship meal May 15, Chili Cook-Off May 16. Warm catering lead.",
        ),
      },
      {
        legacyId: 20,
        org: "Chester Eastside Inc.",
        contact: "Executive Director",
        website: "https://chestereastside.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        gamedate: "2026-10-01",
        source: "Catering CRM",
        followup: d(2),
        notes: note(
          "Harvest Festival October, Volunteer Banquet December. Strong repeat potential.",
        ),
      },
      {
        legacyId: 21,
        org: "City of Chester – Mayor's Office",
        contact: "Mayor's Events Staff",
        website: "https://chestercity.com",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(3),
      },
      {
        legacyId: 22,
        org: "Keystone First Health Plan",
        contact: "Community Outreach Manager",
        website: "https://keystonefirst.com",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(4),
      },
      {
        legacyId: 23,
        org: "Neumann University",
        contact: "Campus Events Manager",
        website: "https://neumann.edu",
        type: "University",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(3),
      },
      {
        legacyId: 24,
        org: "Delaware County Community College",
        contact: "Events Coordinator",
        website: "https://dccc.edu",
        type: "University",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(3),
      },
      {
        legacyId: 25,
        org: "Boys & Girls Club of Chester",
        contact: "Events Coordinator",
        website: "https://bgcchesterpa.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        gamedate: "2026-04-18",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Annual Black Tie Gala at Harrah's. Approach for future catering partnership.",
        ),
      },
      {
        legacyId: 26,
        org: "St. Daniel's Ray of Hope CDC",
        contact: "Executive Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        gamedate: "2026-06-20",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "15th Annual Chester Juneteenth Festival. Pitch Frontline as official catering vendor.",
        ),
      },
      {
        legacyId: 27,
        org: "Delaware County NAACP",
        contact: "Branch President",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(3),
      },
      {
        legacyId: 28,
        org: "CityTeam Ministries Chester",
        contact: "Program Director",
        website: "https://cityteam.org/chester",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note("Daily hot meals at 5pm. Key community relationship."),
      },
      {
        legacyId: 29,
        org: "Salvation Army of Chester",
        contact: "Captain",
        website: "https://salvationarmy.org",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Daily breakfasts and lunches Mon-Fri. Could collaborate on fundraiser dinners.",
        ),
      },
      {
        legacyId: 30,
        org: "Holiday Inn Express – Concordville",
        contact: "Event Sales Manager",
        type: "Hotel/Venue",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(5),
      },
      {
        legacyId: 31,
        org: "Penn Medicine – Chester County Hospital",
        contact: "Volunteer Services",
        website: "https://pennmedicine.org",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Catering CRM",
        followup: d(4),
      },
      {
        legacyId: 32,
        org: "First Baptist Church of Chester",
        contact: "Pastor",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Active congregation with weekly fellowship meals and annual church banquet.",
        ),
      },
      {
        legacyId: 33,
        org: "Mt. Zion A.M.E. Church",
        contact: "Events Committee Chair",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Quarterly church dinners and annual pastor appreciation. Warm community lead.",
        ),
      },
      {
        legacyId: 34,
        org: "Bethel A.M.E. Church – Chester",
        contact: "Church Administrator",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
      },
      {
        legacyId: 35,
        org: "New Jerusalem Church of God in Christ",
        contact: "Youth Director",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Youth night and quarterly revival dinners. Growing congregation.",
        ),
      },
      {
        legacyId: 36,
        org: "Grace Community Church – Chester",
        contact: "Events Coordinator",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 37,
        org: "Chester Housing Authority",
        contact: "Resident Services Coordinator",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Resident appreciation events and seasonal holiday dinners for 2,000+ residents.",
        ),
      },
      {
        legacyId: 38,
        org: "Delaware County Office of Services for the Aging",
        contact: "Program Manager",
        website: "https://delcosa.org",
        type: "Senior Program",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "County nutrition programs. Catering RFP likely in fall. Important relationship.",
        ),
      },
      {
        legacyId: 39,
        org: "Chester Rotary Club",
        contact: "Club President",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Weekly lunch meetings (~40 members) + annual gala fundraiser. High-value lead.",
        ),
      },
      {
        legacyId: 40,
        org: "Chester Lions Club",
        contact: "Club Secretary",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 41,
        org: "Crozer Health Foundation",
        contact: "Events Manager",
        website: "https://crozerhealthfoundation.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Annual gala at hotel. Approach for 2026 gala catering bid.",
        ),
      },
      {
        legacyId: 42,
        org: "Chester Community Improvement Project (CCIP)",
        contact: "Executive Director",
        website: "https://chesterccip.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Neighborhood revitalization org. Partner for community cookouts and events.",
        ),
      },
      {
        legacyId: 43,
        org: "Community Arts Center – Wallingford",
        contact: "Gallery Director",
        website: "https://communityartscenter.org",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Gallery openings and member gala events. Caribbean-themed evening could be signature.",
        ),
      },
      {
        legacyId: 44,
        org: "The Franklin Institute (Events)",
        contact: "Special Events Sales",
        website: "https://fi.edu",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(7),
        notes: note(
          "Major venue — approach for sub-contracting on Caribbean-themed corporate events.",
        ),
      },
      {
        legacyId: 45,
        org: "Chester Creek Arts Center",
        contact: "Executive Director",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 46,
        org: "Media Theatre",
        contact: "House Manager",
        website: "https://mediatheatre.org",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Pre-show and intermission catering. ~200 seats. Opening night receptions.",
        ),
      },
      {
        legacyId: 47,
        org: "Springside Chestnut Hill Academy",
        contact: "Alumni Events Coordinator",
        website: "https://scasd.org",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 48,
        org: "Swarthmore College – Dining Services",
        contact: "Catering Manager",
        website: "https://swarthmore.edu",
        type: "University",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Faculty dinners, alumni weekend events. High-prestige contract opportunity.",
        ),
      },
      {
        legacyId: 49,
        org: "Lincoln University – Student Events",
        contact: "Student Activities Director",
        website: "https://lincoln.edu",
        type: "University",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "HBCU with strong community connection. Homecoming and graduation events.",
        ),
      },
      {
        legacyId: 50,
        org: "Holy Ghost Preparatory School",
        contact: "Alumni Relations",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 51,
        org: "Chester Charter Scholars Academy",
        contact: "Principal / Events",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Charter school with active parent association. Teacher appreciation and fundraiser dinners.",
        ),
      },
      {
        legacyId: 52,
        org: "Harrah Philadelphia Casino – Events",
        contact: "Group Sales Manager",
        website: "https://harrahsphiladelphia.com",
        type: "Hotel/Venue",
        module: "catering",
        status: "Contacted",
        source: "Kimi Research",
        followup: d(7),
        notes: note(
          "Major casino venue 5 min from Frontline. Partnership for overflow catering and Caribbean pop-ups.",
        ),
      },
      {
        legacyId: 53,
        org: "Wyndham Philadelphia – Historic District",
        contact: "Events & Catering Manager",
        type: "Hotel/Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
      },
      {
        legacyId: 54,
        org: "Brandywine Health Foundation",
        contact: "Development Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Annual health equity gala. Strong values alignment with Frontline community mission.",
        ),
      },
      {
        legacyId: 55,
        org: "Delaware County Medical Society",
        contact: "Executive Director",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 56,
        org: "Riddle Hospital Foundation",
        contact: "Special Events Coordinator",
        website: "https://riddle.org",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Annual gala + staff appreciation events. Hospital volunteer luncheons monthly.",
        ),
      },
      {
        legacyId: 57,
        org: "Delaware County Bar Association",
        contact: "Executive Director",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Annual dinner + CLE luncheons. ~300 members. Premium catering opportunity.",
        ),
      },
      {
        legacyId: 58,
        org: "Greater Philadelphia Chamber of Commerce",
        contact: "Events Team",
        website: "https://gpcc.com",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(7),
        notes: note(
          "Networking events and ribbon cuttings. Get listed as preferred caterer.",
        ),
      },
      {
        legacyId: 59,
        org: "Chester Business Alliance",
        contact: "Executive Director",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Local chamber — monthly meetings + Business of the Month dinners. Frontline can host.",
        ),
      },
      {
        legacyId: 60,
        org: "Urban League of Philadelphia",
        contact: "Program Director",
        website: "https://urbanleaguephilly.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Annual gala + workforce dinners. Community partnership with Caribbean-owned business narrative.",
        ),
      },
      {
        legacyId: 61,
        org: "Philadelphia Urban Creators",
        contact: "Director",
        website: "https://phillyurbancreators.com",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 62,
        org: "Chester Economic Development Authority",
        contact: "Business Development Manager",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Economic summits + ribbon cuttings. Frontline as anchor business success story.",
        ),
      },
      {
        legacyId: 63,
        org: "YMCA of Greater Philadelphia – Chester Branch",
        contact: "Branch Director",
        website: "https://ymcagbw.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "After-school programs + adult fitness events. Annual fundraiser gala.",
        ),
      },
      {
        legacyId: 64,
        org: "Habitat for Humanity – Delaware County",
        contact: "Volunteer Coordinator",
        website: "https://habitatdelco.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Build day cookouts and annual awards dinner. Community goodwill + PR opportunity.",
        ),
      },
      {
        legacyId: 65,
        org: "The Arc of Delaware County",
        contact: "Events Coordinator",
        website: "https://arcofdelco.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 66,
        org: "Catholic Social Services – Chester",
        contact: "Regional Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 67,
        org: "Lutheran Social Services – SE Pennsylvania",
        contact: "Program Director",
        website: "https://lsspa.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Volunteer recognition events and senior meal programs. Government grant-funded.",
        ),
      },
      {
        legacyId: 68,
        org: "Chester Upland Coalition for Youth (CUCY)",
        contact: "Youth Program Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Youth sports + academic programs. Summer cookout fundraiser and gala.",
        ),
      },
      {
        legacyId: 69,
        org: "Penns Grove Fire Company",
        contact: "Events Chair",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Annual fundraiser banquet + volunteer appreciation. Great community goodwill.",
        ),
      },
      {
        legacyId: 70,
        org: "Chester Police Athletic League",
        contact: "Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Youth programming — end-of-year celebration and fundraiser dinners.",
        ),
      },
      {
        legacyId: 71,
        org: "Delaware County Veterans Affairs",
        contact: "Veterans Services Director",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Veterans Day and Memorial Day events. Patriotic community catering opportunity.",
        ),
      },
      {
        legacyId: 72,
        org: "American Legion Post 34 – Chester",
        contact: "Post Commander",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 73,
        org: "VFW Post 678 – Upland",
        contact: "Events Coordinator",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 74,
        org: "Delaware County Democratic Committee",
        contact: "Events Coordinator",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Fundraiser dinners and candidate events. Non-partisan approach: offer to Republicans too.",
        ),
      },
      {
        legacyId: 75,
        org: "Tri-State Caribbean American Association",
        contact: "President",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(1),
        notes: note(
          "Direct cultural match — Caribbean festivals, independence day celebrations, meetings. Priority.",
        ),
      },
      {
        legacyId: 76,
        org: "Jamaican American Association of Delaware Valley",
        contact: "Chapter Chair",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(1),
        notes: note(
          "Jamaica Independence Day event and cultural dinners. Perfect brand alignment.",
        ),
      },
      {
        legacyId: 77,
        org: "Caribbean Cultural Center – Philadelphia",
        contact: "Executive Director",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Cultural events + Carnival season. Frontline as go-to Caribbean caterer for region.",
        ),
      },
      {
        legacyId: 78,
        org: "WURD Radio – Philadelphia",
        contact: "Events & Sponsorship Manager",
        website: "https://wurdradio.com",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "African-American radio — sponsorship/catering for live events. Media partnership.",
        ),
      },
      {
        legacyId: 79,
        org: "Chester Made",
        contact: "Co-Founder",
        website: "https://chestermade.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Hyperlocal Chester brand. Pop-up event catering and community showcase partner.",
        ),
      },
      {
        legacyId: 80,
        org: "Crozer Health – Dietary/Catering",
        contact: "Director of Food Services",
        website: "https://crozerhealth.org",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Hospital system RFP for staff events and physician dinners. Large contract potential.",
        ),
      },
      {
        legacyId: 81,
        org: "St. Francis Hospital Foundation",
        contact: "Development Events Coordinator",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 82,
        org: "Glen Mills Schools Foundation",
        contact: "Events Manager",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 83,
        org: "KIPP Philadelphia Schools",
        contact: "Family Engagement Coordinator",
        website: "https://kippphiladelphia.org",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Charter network with family nights and graduation events. Strong community values match.",
        ),
      },
      {
        legacyId: 84,
        org: "Archbishop Carroll High School",
        contact: "Alumni Director",
        website: "https://archbishopcarroll.org",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Alumni reunion and graduation dinner. Catholic school with active events calendar.",
        ),
      },
      {
        legacyId: 85,
        org: "St. James High School – Chester",
        contact: "Principal",
        type: "School",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
      },
      {
        legacyId: 86,
        org: "PA CareerLink – Chester",
        contact: "Center Director",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Job fair catering + graduation ceremonies for workforce training programs.",
        ),
      },
      {
        legacyId: 87,
        org: "Chester Water Authority",
        contact: "Administrative Manager",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Staff appreciation and board meeting catering. Small but steady repeat business.",
        ),
      },
      {
        legacyId: 88,
        org: "Delaware County Emergency Services",
        contact: "Chief / Events Contact",
        type: "City Agency",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
      },
      {
        legacyId: 89,
        org: "United Way of Greater Philadelphia – Delaware County",
        contact: "Events Manager",
        website: "https://unitedforimpact.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Day of Caring and annual luncheon. High-visibility events that put Frontline's brand in front of 100+ orgs.",
        ),
      },
      {
        legacyId: 90,
        org: "Big Brothers Big Sisters – Delaware County",
        contact: "Development Director",
        website: "https://bbbsdelco.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Bowl for Kids Sake and annual gala. Youth-focused mission aligns with Frontline community values.",
        ),
      },
      {
        legacyId: 91,
        org: "Ronald McDonald House – Philadelphia",
        contact: "Special Events Coordinator",
        website: "https://rmhcphiladelphia.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 92,
        org: "March of Dimes – Philadelphia Chapter",
        contact: "March for Babies Chair",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Post-walk celebration catering. Community health mission + Caribbean food = perfect fit.",
        ),
      },
      {
        legacyId: 93,
        org: "Make-A-Wish Foundation – Philadelphia",
        contact: "Events Coordinator",
        website: "https://philadelphia.wish.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
      },
      {
        legacyId: 94,
        org: "Aston Carter – Delaware County Office",
        contact: "Office Manager",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Corporate lunch catering for staffing office. Recurring revenue potential.",
        ),
      },
      {
        legacyId: 95,
        org: "Robert Half – Media, PA",
        contact: "Branch Manager",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 96,
        org: "Siemens – Malvern Campus",
        contact: "Facilities Events Manager",
        website: "https://siemens.com",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(7),
        notes: note(
          "Corporate campus with frequent lunch meetings. Pitch Caribbean lunch catering rotation.",
        ),
      },
      {
        legacyId: 97,
        org: "Aramark Corporation – HQ (internal events)",
        contact: "Internal Events Team",
        website: "https://aramark.com",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(7),
        notes: note(
          "Ironic opportunity — cater for the caterer. Cultural diversity events + holiday parties.",
        ),
      },
      {
        legacyId: 98,
        org: "Sunoco Energy – Marcus Hook",
        contact: "HR / Events Manager",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Industrial site with shift worker appreciation events. Large group orders.",
        ),
      },
      {
        legacyId: 99,
        org: "GlaxoSmithKline – Upper Providence",
        contact: "Corporate Events",
        website: "https://gsk.com",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(7),
        notes: note(
          "Pharma giant with frequent lunch-and-learn catering needs. High-value corporate account.",
        ),
      },
      {
        legacyId: 100,
        org: "Tasty Baking Company – Employee Events",
        contact: "HR Director",
        type: "Local Business",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 101,
        org: "Shore Memorial Yacht Club",
        contact: "Events Coordinator",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Waterfront venue — Caribbean menu is a perfect thematic fit. Wedding season catering.",
        ),
      },
      {
        legacyId: 102,
        org: "Linvilla Orchards – Event Barn",
        contact: "Private Events Manager",
        website: "https://linvilla.com",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Rustic venue with summer/fall events. Caribbean BBQ as a themed catering option.",
        ),
      },
      {
        legacyId: 103,
        org: "Terrain at Styer, contact: Events Coordinator",
        website: "https://shopterrain.com/pages/private-events",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Upscale garden venue. Sub-catering opportunity for weekend weddings and events.",
        ),
      },
      {
        legacyId: 104,
        org: "NovaCare Rehabilitation – Chester",
        contact: "Clinic Manager",
        type: "Medical",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 105,
        org: "SourceAmerica – Regional Office",
        contact: "Regional Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
      },
      {
        legacyId: 106,
        org: "Media Fellowship House",
        contact: "Program Director",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Affordable housing nonprofit — board meetings + community events.",
        ),
      },
      {
        legacyId: 107,
        org: "Chester Community College Foundation",
        contact: "Gala Chair",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Annual scholarship gala. High-prestige event with ~200 attendees.",
        ),
      },
      {
        legacyId: 108,
        org: "Pennsylvania State Corrections Officers Association",
        contact: "Events Committee",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
      },
      {
        legacyId: 109,
        org: "Chester-Upland Athletic Association",
        contact: "President",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Youth sports banquets across multiple sports. High-volume seasonal business.",
        ),
      },
      {
        legacyId: 110,
        org: "Elwyn",
        contact: "Special Events Director",
        website: "https://elwyn.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Disability services org with gala + volunteer events. Inclusive community partner.",
        ),
      },
      // ── BOTH MODULE (Soccer + Catering) ──────────────────
      {
        legacyId: 111,
        org: "Penn Wood High School Athletics",
        contact: "Athletic Director",
        type: "Youth Soccer Team",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Multi-sport school — team banquets (catering) and soccer booster events.",
        ),
      },
      {
        legacyId: 112,
        org: "Interboro High School Sports Boosters",
        contact: "Booster Club President",
        type: "Youth Soccer Team",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Booster club fundraisers + team banquets. Both soccer and catering revenue.",
        ),
      },
      {
        legacyId: 113,
        org: "Delaware County Athletic Directors Association",
        contact: "President",
        type: "Civic Group",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Annual banquet + sports awards. Access to 30+ schools in Delco.",
        ),
      },
      {
        legacyId: 114,
        org: "Springfield High School Soccer Club",
        contact: "Head Coach",
        type: "Youth Soccer Team",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
      },
      {
        legacyId: 115,
        org: "Chichester School District",
        contact: "Community Coordinator",
        type: "School",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "District events (catering) and soccer program (booster banquets).",
        ),
      },
      {
        legacyId: 116,
        org: "Sun Center Studios – Aston",
        contact: "Events Manager",
        type: "Event Venue",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Major film/sports complex near Chester. Corporate events and youth sports showcases.",
        ),
      },
      // ── Additional Soccer Leads (to reach 146) ────────────
      {
        legacyId: 117,
        org: "Union de Foot Philadelphia",
        contact: "Club Secretary",
        type: "Supporter Club",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "French-Caribbean soccer cultural club. Natural cultural fit for Frontline.",
        ),
      },
      {
        legacyId: 118,
        org: "PSP (Philadelphia Soccer Page) – Community",
        contact: "Editor/Community Manager",
        website: "https://phillysoccerpage.net",
        type: "Supporter Club",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Largest Philly soccer media community. Advertise game-day specials + get press coverage.",
        ),
      },
      {
        legacyId: 119,
        org: "Marcus Hook FC",
        contact: "Club Captain",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Local adult amateur club near Chester. Post-match gatherings and end-of-season banquet.",
        ),
      },
      {
        legacyId: 120,
        org: "Upland Athletic Club – Soccer",
        contact: "Head Coach",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 121,
        org: "New York Red Bulls Away Supporters",
        contact: "Travel Coordinator",
        type: "Visiting MLS Team",
        module: "soccer",
        status: "New",
        gamedate: "2025-07-05",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Big away following — offer group pre-match dining package for rival fans.",
        ),
      },
      {
        legacyId: 122,
        org: "Atlanta United FC Away Group",
        contact: "Travel Coordinator",
        type: "Visiting MLS Team",
        module: "soccer",
        status: "New",
        gamedate: "2025-08-02",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 123,
        org: "Charlotte FC Away Supporters",
        contact: "Travel Coordinator",
        type: "Visiting MLS Team",
        module: "soccer",
        status: "New",
        gamedate: "2025-07-19",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 124,
        org: "Greater Philadelphia Soccer Association",
        contact: "President",
        type: "Tournament",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Adult recreational leagues + tournaments across 500+ teams. Major banquet potential.",
        ),
      },
      {
        legacyId: 125,
        org: "Drexel Hill Soccer Club",
        contact: "Club Director",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 126,
        org: "Marple Newtown Soccer Club",
        contact: "Events Volunteer",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 127,
        org: "Haverford Soccer Club",
        contact: "Club Administrator",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 128,
        org: "Ridley Park FC",
        contact: "Head Coach",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 129,
        org: "Westfield Soccer Club – Broomall",
        contact: "Club President",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 130,
        org: "Delaware Rush Soccer Club",
        contact: "Director of Player Development",
        website: "https://delawarerush.com",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Large travel club across DE/PA. End-of-season banquets and tournament weekends.",
        ),
      },
      {
        legacyId: 131,
        org: "FC Bucks Soccer – Warminster",
        contact: "Club Director",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
      },
      {
        legacyId: 132,
        org: "Chester City FC Alumni Association",
        contact: "President",
        type: "Supporter Club",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        notes: note(
          "Alumni of former Chester soccer clubs. Annual reunion dinner — strong local connection.",
        ),
      },
      {
        legacyId: 133,
        org: "National Premier Soccer League (NPSL) – Teams",
        contact: "League Office",
        website: "https://npsl.com",
        type: "Tournament",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(6),
        notes: note(
          "Semi-pro league teams in region. Team travel catering and supporter events.",
        ),
      },
      {
        legacyId: 134,
        org: "Philadelphia SC Corinthians",
        contact: "Club Manager",
        website: "https://phillysc.com",
        type: "Youth Soccer Team",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Brazilian-American soccer club. Cultural connection — Caribbean + Latin food is a fit.",
        ),
      },
      {
        legacyId: 135,
        org: "Global Premier Soccer – Eastern PA",
        contact: "Regional Director",
        website: "https://globalpremier.com",
        type: "Tournament",
        module: "soccer",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Tournament organizer with 50+ events per year in region. Exclusive catering deal possible.",
        ),
      },
      // ── Additional Catering Leads ─────────────────────────
      {
        legacyId: 136,
        org: "Hope Lutheran Church – Aston",
        contact: "Fellowship Committee Chair",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
      },
      {
        legacyId: 137,
        org: "Calvary Chapel – Chester",
        contact: "Youth Pastor",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
      },
      {
        legacyId: 138,
        org: "First Presbyterian Church – Chester City",
        contact: "Church Office Manager",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 139,
        org: "Emmanuel Baptist Church – Linwood",
        contact: "Ministry Events Coordinator",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "150+ member congregation. Annual banquet + senior ministry luncheons.",
        ),
      },
      {
        legacyId: 140,
        org: "Community of Grace Church",
        contact: "Lead Pastor",
        type: "Church",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
      },
      {
        legacyId: 141,
        org: "Chester Cultural Arts Center",
        contact: "Program Director",
        type: "Event Venue",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "Local arts venue seeking catering partner for opening nights and community exhibitions.",
        ),
      },
      {
        legacyId: 142,
        org: "Widener University – Athletics Department",
        contact: "Athletic Director",
        website: "https://widener.edu",
        type: "University",
        module: "both",
        status: "New",
        source: "Kimi Research",
        followup: d(3),
        notes: note(
          "D3 athletics with multiple team banquets (catering) and soccer program (game-day events).",
        ),
      },
      {
        legacyId: 143,
        org: "Delaware County Community Foundation",
        contact: "Grants & Events Director",
        website: "https://delcocf.org",
        type: "Nonprofit",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(4),
        notes: note(
          "Annual luncheon + donor appreciation events. Access to 100s of Delco nonprofits.",
        ),
      },
      {
        legacyId: 144,
        org: "Chester Heritage Festival Committee",
        contact: "Festival Chair",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(2),
        gamedate: "2026-08-15",
        notes: note(
          "Annual summer festival. Frontline as featured food vendor + catering anchor.",
        ),
      },
      {
        legacyId: 145,
        org: "Delaware County Chefs & Restaurateurs Association",
        contact: "President",
        type: "Civic Group",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(5),
        notes: note(
          "Industry networking + restaurant week partnership. Get Frontline on the map.",
        ),
      },
      {
        legacyId: 146,
        org: "Philly Carib Fest – Organizing Committee",
        contact: "Festival Director",
        social: "@PhillyCaribFest",
        type: "Community Partner",
        module: "catering",
        status: "New",
        source: "Kimi Research",
        followup: d(1),
        gamedate: "2026-07-04",
        notes: note(
          "Philadelphia Caribbean Festival — Frontline MUST be the catering partner. Top priority lead.",
        ),
      },
    ];

    // Add default importDate and seqStep where missing
    const finalLeads = seedLeads.map((lead) => ({
      importDate: today,
      seqStep: 0,
      notes: [],
      ...lead,
    }));

    await Lead.bulkCreate(finalLeads);
    console.log(`✅ ${finalLeads.length} seed leads created`);
    console.log("✅ Database seed complete");
  } catch (err) {
    console.error("❌ Seed error:", err.message);
    // Don't crash the server on seed failure
  }
}

module.exports = seedDatabase;
